name: CI
on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip g++ make
      - name: Build with waf
        run: |
          ./waf configure
          ./waf
      - name: Run unit tests
        run: ./build/test/unit/test_bgen
      - name: Build wheel
        run: |
          pip install build
          python -m build --wheel

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
